name: app_prototipo_bioline
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^4.0.5345
  sliding_sheet: ^0.3.7
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  #tflite_flutter_helper:
  #app_prototipo_bioline:
  #  path:
  #   ../../
  camera: ^0.9.4+5
  image_picker: ^0.8.4+4
  collection: ^1.15.0
  logger: ^1.0.0
  tflite_flutter: ^0.9.0
  persistent_bottom_nav_bar: ^4.0.2
  cupertino_icons: ^1.0.4
  video_player: ^2.2.10
  equatable: ^2.0.3
  image: ^3.0.2
  tuple: ^2.0.0
  ffi: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/Launcher_Icon.png"


flutter:
  uses-material-design: true
  

  assets:
    - assets/
    - assets/science/
    - assets/backgrounds/
    - assets/season/
    - assets/brand/
    - assets/models/
  
  #fonts:
  #  - family: Montserrat
  #    fonts:
  #      - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
  #        weight: 500
  #      - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
  #        weight: 600
  #      - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
  #        weight: 700
